-- CreateEnum
CREATE TYPE "RegressionSpecification" AS ENUM ('PRIMARY', 'SECONDARY');

-- CreateTable
CREATE TABLE "RegressionRun" (
    "id" SERIAL NOT NULL,
    "run_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "specification" "RegressionSpecification" NOT NULL,
    "n" INTEGER NOT NULL,
    "min_spend_filter" DOUBLE PRECISION,
    "r_squared" DOUBLE PRECISION NOT NULL,
    "adj_r_squared" DOUBLE PRECISION NOT NULL,
    "f_statistic" DOUBLE PRECISION NOT NULL,
    "f_p_value" DOUBLE PRECISION NOT NULL,
    "residual_std_error" DOUBLE PRECISION NOT NULL,
    "intercept_coef" DOUBLE PRECISION NOT NULL,
    "intercept_se_ols" DOUBLE PRECISION NOT NULL,
    "intercept_se_hc3" DOUBLE PRECISION NOT NULL,
    "intercept_p_ols" DOUBLE PRECISION NOT NULL,
    "intercept_p_hc3" DOUBLE PRECISION NOT NULL,
    "engagement_rate_coef" DOUBLE PRECISION NOT NULL,
    "engagement_rate_se_ols" DOUBLE PRECISION NOT NULL,
    "engagement_rate_se_hc3" DOUBLE PRECISION NOT NULL,
    "engagement_rate_p_ols" DOUBLE PRECISION NOT NULL,
    "engagement_rate_p_hc3" DOUBLE PRECISION NOT NULL,
    "engagement_rate_vif" DOUBLE PRECISION NOT NULL,
    "frequency_coef" DOUBLE PRECISION NOT NULL,
    "frequency_se_ols" DOUBLE PRECISION NOT NULL,
    "frequency_se_hc3" DOUBLE PRECISION NOT NULL,
    "frequency_p_ols" DOUBLE PRECISION NOT NULL,
    "frequency_p_hc3" DOUBLE PRECISION NOT NULL,
    "frequency_vif" DOUBLE PRECISION NOT NULL,
    "ctr_coef" DOUBLE PRECISION NOT NULL,
    "ctr_se_ols" DOUBLE PRECISION NOT NULL,
    "ctr_se_hc3" DOUBLE PRECISION NOT NULL,
    "ctr_p_ols" DOUBLE PRECISION NOT NULL,
    "ctr_p_hc3" DOUBLE PRECISION NOT NULL,
    "ctr_vif" DOUBLE PRECISION NOT NULL,
    "cpm_coef" DOUBLE PRECISION NOT NULL,
    "cpm_se_ols" DOUBLE PRECISION NOT NULL,
    "cpm_se_hc3" DOUBLE PRECISION NOT NULL,
    "cpm_p_ols" DOUBLE PRECISION NOT NULL,
    "cpm_p_hc3" DOUBLE PRECISION NOT NULL,
    "cpm_vif" DOUBLE PRECISION NOT NULL,
    "breusch_pagan_lm" DOUBLE PRECISION NOT NULL,
    "breusch_pagan_p" DOUBLE PRECISION NOT NULL,
    "jarque_bera_jb" DOUBLE PRECISION NOT NULL,
    "jarque_bera_p" DOUBLE PRECISION NOT NULL,
    "jarque_bera_skew" DOUBLE PRECISION NOT NULL,
    "jarque_bera_exkurt" DOUBLE PRECISION NOT NULL,
    "shapiro_wilk_w" DOUBLE PRECISION,
    "shapiro_wilk_p" DOUBLE PRECISION,
    "in_sample_mae" DOUBLE PRECISION,
    "in_sample_rmse" DOUBLE PRECISION,
    "in_sample_mape" DOUBLE PRECISION,
    "cv_r_squared" DOUBLE PRECISION,
    "cv_mae" DOUBLE PRECISION,
    "cv_rmse" DOUBLE PRECISION,
    "cv_mape" DOUBLE PRECISION,
    "baseline_mae" DOUBLE PRECISION,
    "baseline_rmse" DOUBLE PRECISION,
    "baseline_mape" DOUBLE PRECISION,
    "residual_flagged_count" INTEGER,
    "residual_flagged_total_spend" DOUBLE PRECISION,

    CONSTRAINT "RegressionRun_pkey" PRIMARY KEY ("id")
);
