-- AlterTable
ALTER TABLE "FollowerGender" ADD COLUMN "captured_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "FollowerTerritory" ADD COLUMN "captured_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "FollowerAgeGender" ADD COLUMN "captured_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "FollowerAudienceRank" ADD COLUMN "captured_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
